server:
  port: 10001
  servlet:
    context-path: /zzshx

spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  #redis
  redis:
    host: 49.233.85.147
    port: 6379
    timeout: 3000
    key:
      prefix:
        login:
          token: login-token-
  #mysql
  datasource:
    url: jdbc:mysql://49.233.85.147/orderservice?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=Asia/Shanghai
    username: root
    hikari:
      maximum-pool-size: 10
      max-lifetime: 18000000
      minimum-idle: 3
      connection-timeout: 30000
      connection-test-query: SELECT 1
      pool-name: HiKariDataSource
      idle-timeout: 180000
      auto-commit: true
    type: com.zaxxer.hikari.HikariDataSource


mybatis-plus:
  type-aliases-package: com.order.webservice.domain.po
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl