server:
  port: 9001
  servlet:
    context-path: /zzshx

spring:
  #redis
  redis:
    host: 49.233.85.147
    port: 6379
    timeout: 3000
    lettuce:
      pool:
        min-idle: 1
        max-idle: 10
        max-wait: 3
        max-active: 8

  #mysql
  datasource:
    url: jdbc:mysql://49.233.85.147/orderservice?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      auto-commit: true
      idle-timeout: 300000
      connection-timeout: 30000
      connection-test-query: SELECT 1
      pool-name: OrderServiceHikariCP

#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
  type-aliases-package: com.order.webservice.domain