server:
  port: 9001
  servlet:
    context-path: /zzshx

spring:
  #redis
  redis:
    host: 49.233.85.147
    port: 6379
    timeout: 3
    jedis:
      pool:
        min-idle: 1
        max-idle: 10
        max-wait: 3
        max-active: 8